version: '3'

services:
  mongodb:
    image: blazhe/baza-sua:v1  # Updated image tag
    container_name: mongodb-container
    # Define environment variables if necessary
    volumes:
      - mongo-data:/data/db

  express-service:
    image: blazhe/express-sua:v2  # Updated image tag
    container_name: express-container
    ports:
      - "3000:3000"  # Map host port to container port
    # Define environment variables for database connection

volumes:
  mongo-data:

networks:
  shared-network:
